import { lazy, Suspense } from 'react';
import { stops } from '../../models/neighborhood/content.js';
import EnvironmentPanel from './EnvironmentPanel.jsx';
import { GuestEntry } from './GuestEntry.jsx';
import { MissionBoard } from './MissionBoard.jsx';
import { InteractionDialog } from './InteractionDialog.jsx';
import { HelpDialog } from './HelpDialog.jsx';
import { ExploreDialog } from './ExploreDialog.jsx';
import { inventory, missionSummary } from '../../models/neighborhood/missions.js';
import { MiniMap, Logo, Icon } from './GameMap.jsx';
import LoungeDialog from './LoungeDialog.jsx';

const City = lazy(() => import('./CityCanvas.jsx'));
export default function NeighborhoodView({ controller }) {
  const { section, setSection, nearby, ready, error, car, viewMode, player, guests, guest, record, inside, music, musicRef, progress, objective, lightingMode, setLightingMode, environment, lightingModeRef, gameRef, controlsRef, apiRef, pausedRef, select, explore, reset, enterGuest, switchGuest, leaveHub, toggleView, pointerAction, enterLounge, action, nearbyStop, targetId, distance, target, context, setReady, setError, setNearby, setCar, setPlayer } = controller;
  return <div className={`app-shell simulation is-driving ${environment.daylight.night >= 0.5 ? 'is-night' : ''} ${inside ? 'is-office' : ''} ${viewMode === 'lounge' ? 'is-lounge' : ''}`}>
    <header className="site-header"><a className="brand" href="#home" onClick={event => { event.preventDefault(); select('missions'); }} aria-label="Little City journal"><Logo /><span>little<span className="brand-light">city</span><span className="brand-period">.</span></span></a><nav aria-label="City destinations">{stops.map(stop => <button key={stop.id} onClick={() => explore(stop.id)}>{{ cafe: 'Cafe', workshop: 'Repairs', market: 'Market', library: 'Library', lounge: 'Lounge' }[stop.id]}<span /></button>)}</nav><button className="contact-button" onClick={() => select('missions')}>Journal <Icon name="arrow" size={16} /></button></header>
    <main id="home">
      <div className="world-wrap"><Suspense fallback={null}><City controlsRef={controlsRef} apiRef={apiRef} pausedRef={pausedRef} lightingModeRef={lightingModeRef} gameRef={gameRef} musicRef={musicRef} onReady={() => setReady(true)} onError={() => setError(true)} onNearby={setNearby} onMove={setCar} onCharacterMove={setPlayer} onSelect={select} onActivity={record} /></Suspense></div>
      <section className="welcome"><div className="eyebrow">A GOOD DAY TO DO SOME GOOD</div><h1>Little City<span className="serif-word">.</span></h1><div className="hello-line">Shift {progress.day} · {progress.coins} coins</div>{guest && <div className="guest-strip"><button onClick={() => select('missions')} aria-label={`Guest ${guest.name}, open journal`} className="guest-name">{guest.name}</button><button className="mission-button" onClick={() => select('missions')}>Jobs <b>{missionSummary(progress).count}/3</b></button></div>}</section>
      {guest && progress.active && <section className="objective-tracker" aria-label="Current objective"><small>{progress.active ? 'CURRENT JOB' : progress.completed.length === 3 ? 'SHIFT COMPLETE' : 'START HERE'}</small><strong>{objective.title}</strong><span>{distance !== null ? `${distance} m away · gold map marker` : 'Head back outside to continue'}</span><div>Carrying: {inventory(progress) || 'Nothing'}</div>{progress.active === 'coffee' && progress.step === 1 && <div className="cargo-condition">Tray condition <b>{progress.condition}%</b><progress value={progress.condition} max={100} aria-label="Coffee tray condition" /></div>}<button onClick={() => select(objective.location)}>View task →</button></section>}
      <EnvironmentPanel environment={environment} mode={lightingMode} onMode={setLightingMode} />
      <button className="office-access" disabled={!ready || error} onClick={() => inside ? leaveHub() : select('office')}><Icon name="code" size={17} />{inside ? 'Back to city' : 'Enter hub'}<Icon name="arrow" size={15} /></button>
      {error && <div className="scene-error" role="status"><h3>The city needs WebGL.</h3><p>Try a browser with hardware acceleration to play. Your saved jobs are safe; you can still read your journal.</p><button onClick={() => select('missions')}>Open journal</button></div>}
      <div className={`nearby-toast ${nearbyStop && !section ? 'visible' : ''}`} aria-live="polite">{nearbyStop && <><span className="stop-badge" style={{ background: nearbyStop.color }}>{nearbyStop.number || 'HQ'}</span><div><small>NEARBY · STOP TO INTERACT</small><strong>{nearbyStop.name}</strong></div><button onClick={() => select(nearby)}><kbd>E</kbd> Interact <Icon name="arrow" size={16} /></button></>}</div>
      <div className="touch-controls" aria-label={inside ? 'Touch walking controls' : 'Touch driving controls'}>{[['forward', '↑'], ['left', '←'], ['backward', '↓'], ['right', '→']].map(([key, label]) => <button key={key} className={`touch-${key}`} aria-label={inside ? `Walk ${key}` : key === 'forward' ? 'Accelerate' : key === 'backward' ? 'Reverse' : `Steer ${key}`} {...pointerAction(key)}>{label}</button>)}</div>
      {!inside && <button className="touch-brake" {...pointerAction('brake')}>Brake</button>}
      {inside && <><div className="character-hud" aria-label="Character status" data-x={player.x.toFixed(3)} data-z={player.z.toFixed(3)} data-height={player.height.toFixed(3)}><span>ON FOOT / THIRD PERSON</span><strong>{player.action}</strong><small>WASD walk · Shift run · E interact</small></div><div className="character-actions" aria-label="Character actions"><button {...pointerAction('run')}>Hold to run</button><button disabled={player.height > 0.03} onClick={() => apiRef.current?.act('jump')}>Jump</button><button disabled={player.waveTime > 0} onClick={() => apiRef.current?.act('wave')}>{player.waveTime > 0 ? 'Waving…' : 'Wave'}</button></div></>}
      <div className="bottom-hud"><div className="journey-panel"><div className="journey-heading"><span className="eyebrow">NEIGHBORHOOD DIRECTORY</span></div><div className="stop-list">{stops.map(stop => <button key={stop.id} onClick={() => explore(stop.id)}><span className="stop-number">{stop.number}</span><span>{stop.name}</span><Icon name="pin" size={13} /></button>)}</div></div><div className="driving-guide">{inside ? <div className="office-guide"><strong>{viewMode === 'lounge' ? 'Slow down. Stay a while.' : 'Welcome to the community hub.'}</strong><span>WASD walk · Shift run · Space jump · E interact</span></div> : <div><kbd>W A S D</kbd><span>drive</span><kbd>Space</kbd><span>brake</span><kbd>E</kbd><span>interact</span></div>}<small>Drag to look around · scroll to zoom</small></div><MiniMap car={car} target={progress.active ? targetId : null} onSelect={explore} /></div>
    </main>
    <footer className="site-footer"><div className="world-tools"><span className="speed-indicator"><Icon name="car" size={15} /> {Math.round(car.speed * 3.6)} <small>km/h</small></span><button onClick={() => inside ? leaveHub() : toggleView()} aria-label={viewMode === 'drive' ? 'Show world map' : 'Follow the car'}><Icon name="pin" size={16} /><span>{inside ? 'City view' : viewMode === 'drive' ? 'Map view' : 'Follow car'}</span></button><button onClick={() => select('missions')}>Journal</button><button onClick={reset} aria-label="Recover car or reset character"><Icon name="reset" size={16} /><span>Recover</span></button><button onClick={() => select('help')} aria-label="How to play"><Icon name="help" size={17} /></button></div></footer>
    {guest && viewMode === 'lounge' && <button className="lounge-music-button" onClick={() => select('jukebox')}>♫ {!music.enabled ? 'Music coming soon' : music.playing ? music.title : 'Choose some music'} <span>{!music.enabled ? 'Console off' : music.playing ? 'Playing' : 'Music console'}</span></button>}
    {!guest && <GuestEntry error={guests.entryError} profiles={guests.profiles} onEnter={enterGuest} />}
    {guest && section === 'missions' && <MissionBoard guest={guest} storageAvailable={guests.storageAvailable} onClose={() => setSection(null)} onSwitch={switchGuest} onGuide={() => explore('npc:maya')} />}
    {guest && ['lounge', 'jukebox'].includes(section) && <LoungeDialog inside={viewMode === 'lounge'} available={ready && !error} music={music} onEnter={enterLounge} onClose={() => setSection(null)} />}
    {guest && section === 'help' && <HelpDialog onClose={() => setSection(null)} />}
    {guest && section?.startsWith('explore:') && <ExploreDialog id={section.slice(8)} onClose={() => setSection(null)} onJournal={() => select('missions')} />}
    {guest && section && !section.startsWith('explore:') && !['missions', 'help', 'lounge', 'jukebox'].includes(section) && <InteractionDialog key={section + progress.active + progress.step} id={section} guest={guest} context={context} onAction={action} onClose={() => setSection(null)} />}
    <div className={`mission-notification ${guests.notification && !section ? 'visible' : ''}`} role="status" aria-live="polite">{guests.notification && <><span>✦ JOB COMPLETE · +{guests.notification.points} COINS</span><strong>{guests.notification.title}</strong></>}</div>
  </div>;
}
